name: TruffleHog Secret Scan

on:
  pull_request:

concurrency:
  group: trufflehog-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trufflehog:
    if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
    uses: CSPL-CARS24/centralised-repo-devops/.github/workflows/central-trufflehog.yml@master
    with:
      block_on_secrets: false
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.TRUFFLEHOG_SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      pull-requests: write
      issues: write

